# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/colindrewes/dev/GPCP/build/design/PYNQ-Z1.xdc

# Block Designs: bd/picorv32/picorv32.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==picorv32 || ORIG_REF_NAME==picorv32} -quiet] -quiet

# IP: bd/picorv32/ip/picorv32_irqConcat_0/picorv32_irqConcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==picorv32_irqConcat_0 || ORIG_REF_NAME==picorv32_irqConcat_0} -quiet] -quiet

# IP: bd/picorv32/ip/picorv32_porReset_0/picorv32_porReset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==picorv32_porReset_0 || ORIG_REF_NAME==picorv32_porReset_0} -quiet] -quiet

# IP: bd/picorv32/ip/picorv32_processing_system7_0_0/picorv32_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==picorv32_processing_system7_0_0 || ORIG_REF_NAME==picorv32_processing_system7_0_0} -quiet] -quiet

# IP: bd/picorv32/ip/picorv32_psAxiInterconnect_0/picorv32_psAxiInterconnect_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==picorv32_psAxiInterconnect_0 || ORIG_REF_NAME==picorv32_psAxiInterconnect_0} -quiet] -quiet

# IP: bd/picorv32/ip/picorv32_psInterruptController_0/picorv32_psInterruptController_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==picorv32_psInterruptController_0 || ORIG_REF_NAME==picorv32_psInterruptController_0} -quiet] -quiet

# IP: bd/picorv32/ip/picorv32_resetSlice_0/picorv32_resetSlice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==picorv32_resetSlice_0 || ORIG_REF_NAME==picorv32_resetSlice_0} -quiet] -quiet

# IP: bd/picorv32/ip/picorv32_subprocessorClk_0/picorv32_subprocessorClk_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==picorv32_subprocessorClk_0 || ORIG_REF_NAME==picorv32_subprocessorClk_0} -quiet] -quiet

# IP: bd/picorv32/ip/picorv32_xbar_1/picorv32_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==picorv32_xbar_1 || ORIG_REF_NAME==picorv32_xbar_1} -quiet] -quiet

# IP: bd/picorv32/ip/picorv32_auto_pc_2/picorv32_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==picorv32_auto_pc_2 || ORIG_REF_NAME==picorv32_auto_pc_2} -quiet] -quiet

# IP: bd/picorv32/ip/picorv32_auto_pc_1/picorv32_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==picorv32_auto_pc_1 || ORIG_REF_NAME==picorv32_auto_pc_1} -quiet] -quiet

# IP: bd/picorv32/ip/picorv32_auto_pc_3/picorv32_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==picorv32_auto_pc_3 || ORIG_REF_NAME==picorv32_auto_pc_3} -quiet] -quiet

# IP: bd/picorv32/ip/picorv32_picorv32_0/picorv32_picorv32_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==picorv32_picorv32_0 || ORIG_REF_NAME==picorv32_picorv32_0} -quiet] -quiet

# IP: bd/picorv32/ip/picorv32_psBramController_0/picorv32_psBramController_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==picorv32_psBramController_0 || ORIG_REF_NAME==picorv32_psBramController_0} -quiet] -quiet

# IP: bd/picorv32/ip/picorv32_riscvBram_0/picorv32_riscvBram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==picorv32_riscvBram_0 || ORIG_REF_NAME==picorv32_riscvBram_0} -quiet] -quiet

# IP: bd/picorv32/ip/picorv32_riscvBramController_0/picorv32_riscvBramController_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==picorv32_riscvBramController_0 || ORIG_REF_NAME==picorv32_riscvBramController_0} -quiet] -quiet

# IP: bd/picorv32/ip/picorv32_riscvInterconnect_0/picorv32_riscvInterconnect_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==picorv32_riscvInterconnect_0 || ORIG_REF_NAME==picorv32_riscvInterconnect_0} -quiet] -quiet

# IP: bd/picorv32/ip/picorv32_riscvReset_0/picorv32_riscvReset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==picorv32_riscvReset_0 || ORIG_REF_NAME==picorv32_riscvReset_0} -quiet] -quiet

# IP: bd/picorv32/ip/picorv32_xbar_0/picorv32_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==picorv32_xbar_0 || ORIG_REF_NAME==picorv32_xbar_0} -quiet] -quiet

# IP: bd/picorv32/ip/picorv32_auto_ds_0/picorv32_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==picorv32_auto_ds_0 || ORIG_REF_NAME==picorv32_auto_ds_0} -quiet] -quiet

# IP: bd/picorv32/ip/picorv32_auto_pc_0/picorv32_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==picorv32_auto_pc_0 || ORIG_REF_NAME==picorv32_auto_pc_0} -quiet] -quiet

# IP: bd/picorv32/ip/picorv32_auto_us_0/picorv32_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==picorv32_auto_us_0 || ORIG_REF_NAME==picorv32_auto_us_0} -quiet] -quiet

# XDC: bd/picorv32/picorv32_ooc.xdc
